将try-catch区段置于循环之外


异常可能对代码性能产生负面影响，抛出异常并不是一种无需代价的动作。
创建一个异常对象并抛出，然后控制权转移到catch区段或finally区段，甚至转移到调用端。
由于抛出异常需要承担一些代价，所以应当只对出错情况使用异常。
如果将异常用于流程控制，代码无法像常规流程结构那样高效和清晰。
